[project]
name = "quant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
]

[tool.ty.environment]
python = ".venv"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
]
